language: erlang
services:
  - redis
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/releases/download/v0.14.2/Precompiled.zip && unzip -qq Precompiled.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - export MIX_ENV=test
install: mix deps.get
otp_release:
  - 17.0
  - 17.1
script: mix test
notifications:
  email: false